### ISSUE TITLE
Relative position sizing (Feature Request)

### ISSUE THREAD

**Issue by aghering23** [rapmd73/JackrabbitRelay#16]
Would be nice to be able to open positions relative to account size. 
for FTX that would be the 'availableWithoutBorrow' and Binance that would be 'availableBalance' i would say.

Resultant position size calculated:
Absolute Size: If size=500, then the resultant position size will be $500
Factored Sizing: If size=2x, then the resultant position size will be calculated at double the current account balance.

With the option for a maximum size, some exchanges have a max order-size for specific leverage level and for managing your own risk-appitate.

Example:
FTX futures account has $5000 total collateral.
Factored Sizing 20x, No Maximum size
Results in 20 x 5000 = $100.000

FTX futures account has $5000 total collateral.
Factored Sizing 20x, Maximum size = $50.000
Results in 20 x 5000 = $100.000 -> maximum size triggerd -> $50.000

**Comment by rapmd73** [comment]
Jackrabbit relay already does support basic percentage balance in the following format,

> { "Exchange":"ftxus","Market":"Spot","Account":"MAIN","Action":"Buy","Asset":"AAVE/USD","USD":"1%" }

This applies to quote and base as well or percentages can be defined instead of absolute values. Please work on the basis of the balances reported by each Exchange through a unified layer. With respect to margin trading, that is in works already for the main library and being aggressively worked on by its development team. As soon as they have it implemented, it will also be implemented within Jackrabbit Relay.

As to each of the exchange related specific features, I am not aware of them and will need to research some more closely to see if they can be implemented within the framework.

Thank you.
