### ISSUE TITLE
POST Request from curl not working

### ISSUE THREAD

**Issue by TimoD87** [rapmd73/JackrabbitRelay#18]
I'm trying to sent a post request from curl / Siri Shortcuts. It is not working, I also tried postman and always get no response or timeout. In the Logs of JRR I see completly nothing.

I'm trying the following:

curl -H 'Content-Type: application/json' -d '{"Exchange":"ftx","Market":"Spot","Account":"MAIN","Action":"Buy","Asset":"ETH/USD:USD","Base":"0.01"}' -H "Content-Type: application/json; charset=utf-8" -X POST http://3.4.4.5:80

If I switch to GET, I get directly a feedback from the JRR Server with "NO!"

If I'm using the same Payload:
{"Exchange":"ftx","Market":"Spot","Account":"MAIN","Action":"Buy","Asset":"ETH/USD:USD","Base":"0.01"}

and the IP http://3.4.4.5:80

in an Tradingview alert it is perfectly working.

What is wrong with my command, hopefully you can help me, thanks in advance!

Timo

**Comment by rapmd73** [comment]
Hi,

There are quite a few things here that need to be unpacked so it might take more than one message in order to keep things clear and readable.

First let's start with the post issue. Relay is compatible with TradingView's web hook and alert messaging system.

Because of that, the context type needs to be text/plain.

You can find a working program that demonstrates this in the Extras folder called RelayCLI. The actual line that contains the header reference is here,

https://github.com/rapmd73/JackrabbitRelay/blob/c926ed39fc64e3d0dffcd4f5bf73845634ba6723/Extras/RelayCLI#L54

Specifically to your curl and postman issues, using this context type will fix that issue providing you have not established IP filtering through the use of the IPlist.cfg file.

Even with the correct payload / message layout, if you have the IPlist.cfg file in your config folder, the system will not give you any information whatsoever as your IP address most won't match what is required (the default file is for TradingView only). Relay goes out of its way not to help a potential attacker and so it deliberately does not respond to anything at all if everything is not perfectly aligned up to begin with.

Now to address the issues specifically with GET. Relay treats GET as a completely separate context and is linked to the Statistorium. It will always report NO unless the identity system has been established and the charting system has been running for at least a few days to collect information. This is specifically due to being able to protect the system and not compromising any sensitive data. No access at any time is allowed to any of the config or control files, the information used here to begin with is only nonsensitive but it is still enough that additional and aggressive protections are implemented.

Even though relay is not a security program or a firewall maintenance program, security is important and I try my best to make sure that things are done properly and correctly. If there is per chance a bug in the program and it crashes, I tried to make sure that only the default NO message is ever used such that no compromising information can ever be released from the system.

Here is a full list of videos on Jackrabbit Relay that may also provide additional information along with what is in the GitHub folder for documentation,

https://youtube.com/playlist?list=PLG2u5NlMjgy8T4wg26sW98E0esupdxuuo

Please let me know if this information does not resolve your problem.

Thank you.

**Comment by rapmd73** [comment]
Issue resolved... Closing
